female(mary).
female(sandra).
female(juliet).
female(lisa).
female(peter).
female(paul).
male(dick).
male(bob).
male(harry).
parent(bob,lisa).
parent(bob,paul).
parent(bob,mary).
parent(juliet,lisa).
parent(juliet,paul).
parent(juliet,mary).
parent(peter,harry).
parent(lisa,harry).
parent(mary,dick).
parent(mary,sandra).

